version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/MediaBinge-0.0.1-SNAPSHOT.war MediaBinge-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - MediaBinge-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*